name: Deploy to CapRover

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ github.repository }}
    DOCKERFILE: Dockerfile
    CAPROVER_APP: niumedia-web

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Set Repository and Image Name
              run: |
                REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
                IMAGE_NAME=$DOCKER_USERNAME/$REPO_NAME
                echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
                echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
                echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
                echo "FULL_IMAGE_NAME=$REPO_NAME:$(date +%s)" >> $GITHUB_ENV
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            - uses: actions/checkout@v1
            - run: |
                  echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
                  echo "FULL_IMAGE_NAME=$IMAGE_NAME:$(date +%s)" >> $GITHUB_ENV
            
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and Push Release to DockerHub
              shell: bash
              run: .github/scripts/build_and_push.sh
            - name: Deploy to CapRover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: ${{ secrets.CAPROVER_HOST }}
                  app: ${{ env.CAPROVER_APP }}
                  token: '${{ secrets.CAPROVER_APP_TOKEN }}'
                  image: '${{ env.FULL_IMAGE_NAME }}'

